import {
  ArchiveIcon,
  BarChartIcon,
  CopyIcon,
  CounterClockwiseClockIcon,
  CrossCircledIcon,
  DashboardIcon,
  ExclamationTriangleIcon,
  GearIcon,
  HomeIcon,
  InfoCircledIcon,
  LightningBoltIcon,
  MixIcon,
  ShuffleIcon,
  TableIcon,
  TextAlignBottomIcon,
  UpdateIcon,
} from '@radix-ui/react-icons'
import {
  BookOpenIcon,
  CircleDollarSignIcon,
  CombineIcon,
  CpuIcon,
  DatabaseZapIcon,
  FilePlus2Icon,
  Grid2x2CheckIcon,
  HardDriveIcon,
  KeyIcon,
  RollerCoasterIcon,
  ScrollTextIcon,
  ShieldAlertIcon,
  ShieldIcon,
  UngroupIcon,
  UnplugIcon,
  UsersIcon,
  ZapIcon,
} from 'lucide-react'

import type { MenuItem } from '@/components/menu/types'

export const menuItemsConfig: MenuItem[] = [
  {
    title: 'Overview',
    href: '/overview',
    icon: HomeIcon,
    section: 'main',
  },
  {
    title: 'Queries',
    href: '',
    countKey: 'running-queries',
    icon: MixIcon,
    section: 'main',
    items: [
      {
        title: 'Running Queries',
        href: '/running-queries',
        description:
          'Real-time view of currently executing queries with progress tracking',
        countKey: 'running-queries',
        icon: MixIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/processes',
      },
      {
        title: 'History Queries',
        href: '/history-queries',
        description:
          'Historical query log with execution metrics, memory usage, and performance data',
        icon: CounterClockwiseClockIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_log',
      },
      {
        title: 'Failed Queries',
        href: '/failed-queries',
        description:
          'Query execution failures with error details and stack traces',
        icon: CrossCircledIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_log',
      },
      {
        title: 'Recent Errors',
        href: '/common-errors',
        description:
          'Most frequently occurring errors with timestamps and error messages',
        icon: CrossCircledIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/errors',
      },
      {
        title: 'Most Expensive Queries',
        href: '/expensive-queries',
        description:
          'Resource-intensive queries ranked by CPU, memory, and duration',
        icon: CircleDollarSignIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_log',
      },
      {
        title: 'Expensive by Memory',
        href: '/expensive-queries-by-memory',
        description: 'Queries with highest memory consumption for optimization',
        icon: CircleDollarSignIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_log',
      },
      {
        title: 'New Parts Created',
        href: '/charts?name=new-parts-created',
        description: 'Part creation frequency for MergeTree table optimization',
        icon: FilePlus2Icon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/part_log',
      },
      {
        title: 'Explain',
        href: '/explain',
        description: 'Query execution plan analysis for performance tuning',
        icon: InfoCircledIcon,
        docs: 'https://clickhouse.com/docs/en/sql-reference/statements/explain',
      },
      {
        title: 'Query Cache',
        href: '/query-cache',
        description: 'Cache hit/miss statistics and performance impact',
        icon: DatabaseZapIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_log',
      },
      {
        title: 'Thread Analysis',
        href: '/queries/thread-analysis',
        description:
          'Thread-level query performance breakdown and parallelization',
        icon: CpuIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_thread_log',
      },
      {
        title: 'Parallelization',
        href: '/queries/parallelization',
        description:
          'Parallel query execution effectiveness and thread utilization',
        icon: ZapIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_thread_log',
      },
    ],
  },
  {
    title: 'Tables',
    href: '/tables',
    icon: TableIcon,
    section: 'main',
    items: [
      {
        title: 'Database Explorer',
        href: '/explorer',
        description: 'Interactive database schema browser with metadata',
        icon: TableIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/databases',
      },
      {
        title: 'Tables Overview',
        href: '/tables-overview',
        countKey: 'tables-overview',
        description: 'Table storage statistics with part counts and sizes',
        icon: Grid2x2CheckIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/parts',
      },
      {
        title: 'DDL Queue',
        href: '/distributed-ddl-queue',
        countKey: 'distributed-ddl-queue',
        description: 'Cluster-wide DDL task queue status and execution history',
        icon: ShuffleIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/distributed_ddl_queue',
      },
      {
        title: 'Table Replicas',
        href: '/replicas',
        description: 'Replicated table health status and lag metrics',
        countKey: 'table-replicas',
        icon: CopyIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/replicas',
      },
      {
        title: 'Replication Queue',
        href: '/replication-queue',
        description:
          'Pending and in-progress replication tasks from Keeper/ZooKeeper',
        countKey: 'replication-queue',
        icon: ShuffleIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/replication_queue',
      },
      {
        title: 'Readonly Tables',
        href: '/readonly-tables',
        description: 'Tables in read-only mode with replica status',
        countKey: 'readonly-tables',
        countVariant: 'destructive',
        icon: ExclamationTriangleIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/replicas',
      },
      {
        title: 'Top Usage Tables',
        href: '/top-usage-tables',
        description: 'Table access frequency for identifying hot data',
        icon: TextAlignBottomIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_log',
      },
      {
        title: 'Projections',
        href: '/projections',
        description: 'Projection definitions and usage statistics',
        icon: DatabaseZapIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/projections',
      },
      {
        title: 'View Refreshes',
        href: '/view-refreshes',
        description:
          'Materialized view refresh schedules and execution history',
        countKey: 'view-refreshes',
        icon: UpdateIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/view_refreshes',
      },
      {
        title: 'Part Info',
        href: '/part-info',
        description: 'Active part details with levels and sizes',
        icon: DatabaseZapIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/parts',
      },
      {
        title: 'Dictionaries',
        href: '/dictionaries',
        description: 'External dictionary status and memory usage',
        icon: BookOpenIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/dictionaries',
      },
    ],
  },
  {
    title: 'Merges',
    href: '/merges',
    countKey: 'merges',
    icon: CombineIcon,
    section: 'main',
    items: [
      {
        title: 'Merges',
        href: '/merges',
        description: 'Active merge and mutation operations with progress',
        countKey: 'merges',
        icon: CombineIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/merges',
      },
      {
        title: 'Merge Performance',
        href: '/merge-performance',
        description: 'Historical merge operation statistics and trends',
        icon: LightningBoltIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/part_log',
      },
      {
        title: 'Mutations',
        href: '/mutations',
        description: 'Table mutation status with progress and failures',
        icon: UpdateIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/mutations',
      },
    ],
  },
  {
    title: 'Monitoring',
    href: '',
    icon: BarChartIcon,
    section: 'main',
    items: [
      {
        title: 'Metrics',
        href: '/metrics',
        description: 'Real-time server metrics and counters',
        icon: BarChartIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/metrics',
      },
      {
        title: 'Async Metrics',
        href: '/asynchronous-metrics',
        description: 'Background-calculated metrics for resource monitoring',
        icon: BarChartIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/asynchronous_metrics',
      },
      {
        title: 'Custom Dashboard',
        href: '/dashboard',
        description: 'Build custom monitoring dashboards with charts',
        icon: DashboardIcon,
      },
      {
        title: 'Profiler',
        href: '/profiler',
        description: 'CPU profiling data for query performance analysis',
        icon: CpuIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/processors_profile_log',
      },
    ],
  },
  {
    title: 'Security',
    href: '',
    icon: ShieldIcon,
    section: 'others',
    isNew: true,
    items: [
      {
        title: 'Sessions',
        href: '/security/sessions',
        description: 'User session history with authentication details',
        icon: UsersIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/session_log',
      },
      {
        title: 'Login Attempts',
        href: '/security/login-attempts',
        description: 'Authentication events with failure reasons',
        icon: KeyIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/session_log',
      },
      {
        title: 'Audit Log',
        href: '/security/audit-log',
        description: 'Security-related events and access control',
        icon: ShieldIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/opentelemetry_event_log',
      },
    ],
  },
  {
    title: 'Logs',
    href: '',
    icon: ScrollTextIcon,
    section: 'others',
    isNew: true,
    items: [
      {
        title: 'Text Log',
        href: '/logs/text-log',
        description: 'Server logs with query context and stack traces',
        icon: ScrollTextIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/text_log',
      },
      {
        title: 'Stack Traces',
        href: '/logs/stack-traces',
        description: 'Live thread stack traces for debugging',
        icon: ScrollTextIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/stack_trace',
      },
      {
        title: 'Crashes',
        href: '/logs/crashes',
        description: 'Historical crash reports with diagnostics',
        icon: ShieldAlertIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/crash_log',
      },
    ],
  },
  {
    title: 'System',
    href: '',
    icon: GearIcon,
    section: 'others',
    items: [
      {
        title: 'Settings',
        href: '/settings',
        description: 'Server configuration settings and current values',
        icon: GearIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/settings',
      },
      {
        title: 'MergeTree Settings',
        href: '/mergetree-settings',
        description: 'MergeTree engine-specific settings',
        icon: TableIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/merge_tree_settings',
      },
      {
        title: 'Disks',
        href: '/disks',
        description: 'Storage disk configuration and usage',
        countKey: 'disks',
        icon: HardDriveIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/disks',
      },
    ],
  },
  {
    title: 'Cluster',
    href: '',
    icon: UngroupIcon,
    section: 'others',
    items: [
      {
        title: 'Clusters',
        href: '/clusters',
        description: 'Cluster configuration and member information',
        icon: UngroupIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/clusters',
      },
      {
        title: 'Zookeeper',
        href: '/zookeeper?path=/',
        description:
          'ZooKeeper/Keeper data browser for distributed coordination',
        icon: RollerCoasterIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/zookeeper',
      },
      {
        title: 'Connections',
        href: '/charts?name=connections-http,connections-interserver',
        description: 'Client and inter-server connection metrics',
        icon: UnplugIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/metrics',
      },
    ],
  },
  {
    title: 'Operations',
    href: '',
    icon: ArchiveIcon,
    section: 'others',
    items: [
      {
        title: 'Backups',
        href: '/backups',
        description: 'Backup operation history with status and sizes',
        countKey: 'backups',
        icon: ArchiveIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/backup_log',
      },
      {
        title: 'Errors',
        href: '/errors',
        description: 'Detailed error events with stack traces',
        icon: ShieldAlertIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/error_log',
      },
      {
        title: 'Page Views',
        href: '/page-views',
        description: 'Dashboard usage analytics',
        icon: BarChartIcon,
      },
      {
        title: 'About',
        href: '/about',
        description: 'Dashboard and server version information',
        icon: InfoCircledIcon,
      },
    ],
  },
]
