apiVersion: v2
name: chmonitor
description: A Helm chart for the chmonitor dashboard
type: application
version: 0.2.11
appVersion: 0.2.11
home: https://github.com/duyet/clickhouse-monitoring
sources:
  - https://github.com/duyet/clickhouse-monitoring
maintainers:
  - name: duyet
    email: bot@duyet.net
keywords:
  - clickhouse
  - monitoring
  - dashboard
  - observability
