import { defineConfig, defineDocs } from 'fumadocs-mdx/config'

// Content is generated by scripts/sync-docs.mjs from ../../docs/content/** (the
// committed source of truth). The generated content/docs/** directory is gitignored.
export const docs = defineDocs({
  dir: 'content/docs',
  docs: {
    postprocess: {
      includeProcessedMarkdown: true,
    },
  },
})

export default defineConfig()
