import { defineCollection } from 'astro:content'
import { docsLoader } from '@astrojs/starlight/loaders'
import { docsSchema } from '@astrojs/starlight/schema'

// Native Starlight docs collection. Files under src/content/docs/** are
// generated by scripts/sync-docs.mjs from docs/content/** (gitignored).
export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
}
