import type { DeclarativeQueryConfig } from '../../schema'

import { QUERY_COMMENT } from '@chm/clickhouse-client/constants'

export const keeperLogDeclarative: DeclarativeQueryConfig = {
  name: 'keeper-log',
  defaultView: 'auto',
  card: { primary: 'path', badges: ['type'] },
  description:
    'Per-request log of parameters sent to ZooKeeper/Keeper and the responses received. Requires <zookeeper_log> in server config (often absent in default installs). https://clickhouse.com/docs/en/operations/system-tables/zookeeper_log',
  optional: true,
  tableCheck: 'system.zookeeper_log',
  docs: 'https://clickhouse.com/docs/en/operations/system-tables/zookeeper_log',
  sql: [
    {
      since: '23.3',
      sql: `
        ${QUERY_COMMENT}
        SELECT
          event_time,
          thread_id,
          query_id,
          toString(address) AS address,
          port,
          session_id,
          xid,
          type,
          op_num,
          path,
          data,
          is_ephemeral,
          is_sequential,
          has_watch,
          version,
          requests_size,
          request_idx,
          zxid,
          error,
          watch_type,
          watch_state,
          path_created,
          stat_czxid,
          stat_mzxid,
          stat_pzxid,
          stat_version,
          stat_cversion,
          stat_dataLength,
          stat_numChildren,
          children
        FROM system.zookeeper_log
        WHERE event_time >= now() - INTERVAL 7 DAY
        ORDER BY event_time DESC
        LIMIT 1000
      `,
    },
    {
      since: '23.11',
      sql: `
        ${QUERY_COMMENT}
        SELECT
          hostname,
          event_time,
          thread_id,
          query_id,
          toString(address) AS address,
          port,
          session_id,
          xid,
          type,
          op_num,
          path,
          data,
          is_ephemeral,
          is_sequential,
          has_watch,
          version,
          requests_size,
          request_idx,
          zxid,
          error,
          watch_type,
          watch_state,
          path_created,
          stat_czxid,
          stat_mzxid,
          stat_pzxid,
          stat_version,
          stat_cversion,
          stat_dataLength,
          stat_numChildren,
          children
        FROM system.zookeeper_log
        WHERE event_time >= now() - INTERVAL 7 DAY
        ORDER BY event_time DESC
        LIMIT 1000
      `,
    },
  ],
  columns: [
    'hostname',
    'event_time',
    'thread_id',
    'query_id',
    'address',
    'port',
    'session_id',
    'xid',
    'type',
    'op_num',
    'path',
    'data',
    'is_ephemeral',
    'is_sequential',
    'has_watch',
    'version',
    'requests_size',
    'request_idx',
    'zxid',
    'error',
    'watch_type',
    'watch_state',
    'path_created',
    'stat_czxid',
    'stat_mzxid',
    'stat_pzxid',
    'stat_version',
    'stat_cversion',
    'stat_dataLength',
    'stat_numChildren',
    'children',
  ],
  columnFormats: {
    hostname: 'text',
    event_time: 'related-time',
    thread_id: 'number',
    query_id: 'text',
    address: 'text',
    port: 'number',
    session_id: 'number',
    xid: 'number',
    type: 'colored-badge',
    op_num: 'colored-badge',
    path: 'code',
    data: 'text',
    is_ephemeral: 'boolean',
    is_sequential: 'boolean',
    has_watch: 'boolean',
    version: 'number',
    requests_size: 'number',
    request_idx: 'number',
    zxid: 'number',
    error: 'colored-badge',
    watch_type: 'colored-badge',
    watch_state: 'colored-badge',
    path_created: 'code',
    stat_czxid: 'number',
    stat_mzxid: 'number',
    stat_pzxid: 'number',
    stat_version: 'number',
    stat_cversion: 'number',
    stat_dataLength: 'number',
    stat_numChildren: 'number',
    children: 'text',
  },
}
