export const AGENT_JSON_RENDER_MAX_SPEC_PARTS = 80
export const AGENT_JSON_RENDER_MAX_SPEC_PART_BYTES = 24 * 1024
export const AGENT_JSON_RENDER_MAX_SPEC_BYTES = 160 * 1024
export const AGENT_JSON_RENDER_MAX_ELEMENT_COUNT = 200
