import {
  Loader2,
  User,
  Github,
  Chrome,
  Database,
  Server,
  BarChart3,
  Settings,
  LogOut,
  Search,
  Plus,
  Edit,
  Trash2,
  Shield,
  Key,
  Building,
  Users,
  Lock,
  Eye,
  EyeOff,
  Copy,
  Check,
  AlertCircle,
  Info,
  ChevronDown,
  ChevronRight,
  Home,
  Overview,
  Tables,
  Clusters,
  RunningQueries,
  Explorer,
} from 'lucide-react'

export const Icons = {
  spinner: Loader2,
  user: User,
  gitHub: Github,
  google: Chrome,
  database: Database,
  server: Server,
  barChart3: BarChart3,
  settings: Settings,
  logOut: LogOut,
  search: Search,
  plus: Plus,
  edit: Edit,
  trash2: Trash2,
  shield: Shield,
  key: Key,
  building: Building,
  users: Users,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  copy: Copy,
  check: Check,
  alertCircle: AlertCircle,
  info: Info,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  home: Home,
  overview: Overview,
  tables: Tables,
  clusters: Clusters,
  runningQueries: RunningQueries,
  explorer: Explorer,
}
