import {
  ArchiveIcon,
  BarChartIcon,
  CopyIcon,
  CounterClockwiseClockIcon,
  CrossCircledIcon,
  DashboardIcon,
  ExclamationTriangleIcon,
  GearIcon,
  HomeIcon,
  InfoCircledIcon,
  LightningBoltIcon,
  MixIcon,
  ShuffleIcon,
  TableIcon,
  UpdateIcon,
} from '@radix-ui/react-icons'
import {
  AlertTriangleIcon,
  BookOpenIcon,
  CircleDollarSignIcon,
  CloudIcon,
  CombineIcon,
  CpuIcon,
  DownloadIcon,
  EyeIcon,
  GaugeIcon,
  GitCompareArrowsIcon,
  Grid2x2CheckIcon,
  HardDriveIcon,
  HeartPulseIcon,
  KeyIcon,
  LayersIcon,
  MoveIcon,
  RollerCoasterIcon,
  RssIcon,
  ScrollTextIcon,
  ShieldAlertIcon,
  ShieldIcon,
  SlidersHorizontalIcon,
  SparklesIcon,
  TerminalIcon,
  Trash2Icon,
  TrendingUpIcon,
  UngroupIcon,
  UnplugIcon,
  UsersIcon,
} from 'lucide-react'

import type { MenuItem } from '@/components/menu/types'

import { PeerDBLogo } from '@/components/icons/peerdb-brand-logo'
import { EVENTS_TABLE } from '@/lib/app-tables'
import { DOCS_SITE_URL } from '@/lib/docs-site'

export const menuItemsConfig: MenuItem[] = [
  {
    title: 'Overview',
    href: '/overview',
    icon: HomeIcon,
    section: 'main',
    permission: { feature: 'overview' },
  },
  {
    title: 'AI Agent',
    href: '/agents',
    icon: SparklesIcon,
    section: 'main',
    isNew: true,
    // The chat UI renders for everyone; the backend enforces auth on send (see
    // AgentAuthGate / the /api/v1/agent route), not the client route gate.
    permission: { feature: 'agent' },
  },
  {
    title: 'Insights',
    href: '/insights',
    icon: TrendingUpIcon,
    section: 'main',
    isNew: true,
    permission: { feature: 'insights' },
  },
  {
    title: 'Health',
    href: '/health',
    icon: HeartPulseIcon,
    section: 'main',
    permission: { feature: 'health' },
  },
  {
    title: 'Queries',
    href: '',
    countKey: 'running-queries',
    icon: MixIcon,
    section: 'main',
    permission: { feature: 'queries' },
    items: [
      {
        title: 'Running Queries',
        href: '/running-queries',
        description:
          'Real-time view of currently executing queries with progress tracking',
        countKey: 'running-queries',
        countLabel: 'running',
        icon: MixIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/processes',
        tableCheck: 'system.processes',
      },
      {
        title: 'History Queries',
        href: '/history-queries',
        description:
          'Historical query log with execution metrics, memory usage, and performance data',
        icon: CounterClockwiseClockIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_log',
        tableCheck: 'system.query_log',
      },
      {
        title: 'Failed Queries',
        href: '/failed-queries',
        description:
          'Query execution failures with error details and stack traces',
        icon: CrossCircledIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_log',
        tableCheck: 'system.query_log',
      },
      {
        title: 'Most Expensive Queries',
        href: '/expensive-queries',
        description:
          'Resource-intensive queries ranked by CPU, memory, and duration',
        icon: CircleDollarSignIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_log',
        tableCheck: 'system.query_log',
      },
      {
        title: 'Slow Queries',
        href: '/slow-queries',
        description: 'Top 10 slowest finished queries by duration',
        icon: CounterClockwiseClockIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_log',
        tableCheck: 'system.query_log',
      },
      {
        title: 'Explain',
        href: '/explain',
        description: 'Query execution plan analysis for performance tuning',
        icon: InfoCircledIcon,
        docs: 'https://clickhouse.com/docs/en/sql-reference/statements/explain',
      },
      {
        title: 'Query Views Log',
        href: '/query-views-log',
        description:
          'Materialized view execution history with status, duration, and row throughput',
        icon: CounterClockwiseClockIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_views_log',
        tableCheck: 'system.query_views_log',
      },
      {
        title: 'Thread & Parallelization',
        href: '/queries/thread-analysis',
        description:
          'Thread-level performance breakdown and parallel execution analysis',
        icon: CpuIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_thread_log',
        tableCheck: 'system.query_thread_log',
      },
      {
        title: 'User Processes',
        href: '/user-processes',
        description: 'Per-user memory usage and resource summary',
        icon: UsersIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/user_processes',
        tableCheck: 'system.user_processes',
      },
      {
        title: 'Query Metric Log',
        href: '/query-metric-log',
        description:
          'Per-query resource timeline: memory, CPU, and rows sampled over each query lifetime',
        icon: GaugeIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_metric_log',
        tableCheck: 'system.query_metric_log',
      },
      {
        title: 'Query Cache',
        href: '/query-cache',
        description:
          'Cached query results: cache entries, result sizes, and staleness',
        icon: LightningBoltIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_cache',
        tableCheck: 'system.query_cache',
      },
      {
        title: 'Query Condition Cache',
        href: '/query-condition-cache',
        description:
          'Cached WHERE-clause conditions for repeated query optimization (ClickHouse 25.3+)',
        icon: LightningBoltIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/query_condition_cache',
        tableCheck: 'system.query_condition_cache',
      },
    ],
  },
  {
    title: 'Tables',
    href: '/tables',
    icon: TableIcon,
    section: 'main',
    permission: { feature: 'tables' },
    items: [
      {
        title: 'Data Explorer',
        href: '/explorer',
        description: 'Interactive database schema browser with metadata',
        countKey: 'tables-explorer',
        countLabel: 'tables',
        icon: TableIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/databases',
        tableCheck: ['system.databases', 'system.tables'],
      },
      {
        title: 'SQL Console',
        href: '/sql',
        description:
          'Run read-only SQL with history, EXPLAIN, query log and scan analysis',
        icon: TerminalIcon,
        docs: 'https://clickhouse.com/docs/en/sql-reference/statements/select',
      },
      {
        title: 'Tables Overview',
        href: '/tables-overview',
        countKey: 'tables-overview',
        countLabel: 'tables',
        description: 'Table storage statistics with part counts and sizes',
        icon: Grid2x2CheckIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/parts',
        tableCheck: 'system.parts',
      },
      {
        title: 'DDL Queue',
        href: '/distributed-ddl-queue',
        countKey: 'distributed-ddl-queue',
        countLabel: 'pending',
        description: 'Cluster-wide DDL task queue status and execution history',
        icon: ShuffleIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/distributed_ddl_queue',
        tableCheck: 'system.distributed_ddl_queue',
      },
      {
        title: 'Table Replicas',
        href: '/replicas',
        description: 'Replicated table health status and lag metrics',
        countKey: 'table-replicas',
        countLabel: 'replicas',
        icon: CopyIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/replicas',
        tableCheck: 'system.replicas',
      },
      {
        title: 'Replication Queue',
        href: '/replication-queue',
        description:
          'Pending and in-progress replication tasks from Keeper/ZooKeeper',
        countKey: 'replication-queue',
        countLabel: 'pending',
        icon: ShuffleIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/replication_queue',
        tableCheck: 'system.replication_queue',
      },
      {
        title: 'Replicated Fetches',
        href: '/replicated-fetches',
        description:
          'Currently executing background part downloads from replica sources',
        icon: DownloadIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/replicated_fetches',
        tableCheck: 'system.replicated_fetches',
      },
      {
        title: 'Readonly Tables',
        href: '/readonly-tables',
        description: 'Tables in read-only mode with replica status',
        countKey: 'readonly-tables',
        countLabel: 'readonly',
        countVariant: 'destructive',
        icon: ExclamationTriangleIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/replicas',
        tableCheck: 'system.replicas',
      },
      {
        title: 'Dropped Tables',
        href: '/dropped-tables',
        description:
          'Tables awaiting final asynchronous drop (Atomic database engine)',
        icon: Trash2Icon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/dropped_tables',
        tableCheck: 'system.dropped_tables',
      },
      {
        title: 'Dictionaries',
        href: '/dictionaries',
        description: 'External dictionary status and memory usage',
        countKey: 'dictionaries',
        countLabel: 'dictionaries',
        icon: BookOpenIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/dictionaries',
        tableCheck: 'system.dictionaries',
      },
      {
        title: 'Kafka Consumers',
        href: '/kafka-consumers',
        description:
          'Kafka table engine consumer lag, poll/commit activity, and ingestion errors',
        icon: RssIcon,
        tableCheck: 'system.kafka_consumers',
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/kafka',
      },
      {
        title: 'Detached Parts',
        href: '/detached-parts',
        description:
          'Parts detached from tables, awaiting attach, drop, or inspection',
        icon: UnplugIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/detached_parts',
        tableCheck: 'system.detached_parts',
      },
      {
        title: 'View Refreshes',
        href: '/view-refreshes',
        description:
          'Refreshable materialized view schedules, status, and last-refresh results',
        icon: UpdateIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/view_refreshes',
        tableCheck: 'system.view_refreshes',
      },
    ],
  },
  {
    title: 'Merges',
    href: '/merges',
    countKey: 'merges',
    countLabel: 'active',
    icon: CombineIcon,
    section: 'main',
    permission: { feature: 'operations' },
    items: [
      {
        title: 'Merges',
        href: '/merges',
        description: 'Active merge and mutation operations with progress',
        countKey: 'merges',
        countLabel: 'active',
        icon: CombineIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/merges',
        tableCheck: 'system.merges',
      },
      {
        title: 'Merge Performance',
        href: '/merge-performance',
        description: 'Historical merge operation statistics and trends',
        icon: LightningBoltIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/part_log',
        tableCheck: 'system.part_log',
      },
      {
        title: 'Mutations',
        href: '/mutations',
        description: 'Table mutation status with progress and failures',
        icon: UpdateIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/mutations',
        tableCheck: 'system.mutations',
      },
      {
        title: 'Moves',
        href: '/moves',
        description:
          'In-progress part moves between disks and volumes (TTL / storage policy)',
        icon: MoveIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/moves',
        tableCheck: 'system.moves',
      },
      {
        title: 'Part Log',
        href: '/part-log',
        description:
          'Part lifecycle timeline: creations, merges, mutations, downloads, and removals',
        icon: LayersIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/part_log',
        tableCheck: 'system.part_log',
      },
    ],
  },
  {
    title: 'Metrics',
    href: '',
    icon: BarChartIcon,
    section: 'main',
    items: [
      {
        title: 'Metrics',
        href: '/metrics',
        description: 'Real-time server metrics and counters',
        countKey: 'metrics',
        countLabel: 'metrics',
        icon: BarChartIcon,
        permission: { feature: 'metrics' },
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/metrics',
        tableCheck: 'system.metrics',
      },
      {
        title: 'Async Metrics',
        href: '/asynchronous-metrics',
        description: 'Background-calculated metrics for resource monitoring',
        icon: BarChartIcon,
        permission: { feature: 'metrics' },
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/asynchronous_metrics',
        tableCheck: 'system.asynchronous_metrics',
      },
      {
        title: 'Profiler',
        href: '/profiler',
        description: 'CPU profiling data for query performance analysis',
        icon: CpuIcon,
        isNew: true,
        permission: { feature: 'metrics' },
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/processors_profile_log',
        tableCheck: 'system.processors_profile_log',
      },
    ],
  },
  {
    title: 'Keeper',
    href: '',
    icon: RollerCoasterIcon,
    section: 'main',
    isNew: true,
    items: [
      {
        title: 'Overview',
        href: '/keeper/overview',
        description:
          'Keeper health at a glance: liveness, request load, latency, and per-node cluster state',
        icon: HeartPulseIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/zookeeper_info',
        tableCheck: 'system.zookeeper_info',
      },
      {
        title: 'Data Browser',
        href: '/keeper?path=/',
        description:
          'Browse the ZooKeeper/Keeper znode tree for distributed coordination',
        icon: RollerCoasterIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/zookeeper',
        tableCheck: 'system.zookeeper',
      },
      {
        title: 'Keeper Info',
        href: '/keeper/info',
        description:
          'Cluster-health introspection of every Keeper node: role, latency, raft log, znode counts',
        icon: InfoCircledIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/zookeeper_info',
        tableCheck: 'system.zookeeper_info',
      },
      {
        title: 'Connections',
        href: '/keeper/connections',
        description:
          'Live connections from this ClickHouse server to Keeper/ZooKeeper',
        icon: UnplugIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/zookeeper_connection',
        tableCheck: 'system.zookeeper_connection',
      },
      {
        title: 'Connection Log',
        href: '/keeper/connection-log',
        description:
          'History of Keeper/ZooKeeper connect and disconnect events with reasons',
        icon: CounterClockwiseClockIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/zookeeper_connection_log',
        tableCheck: 'system.zookeeper_connection_log',
      },
      {
        title: 'Request Log',
        href: '/keeper/log',
        description:
          'Per-request log of Keeper/ZooKeeper operations and responses (requires <zookeeper_log>)',
        icon: ScrollTextIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/zookeeper_log',
        tableCheck: 'system.zookeeper_log',
      },
      {
        title: 'Watches',
        href: '/keeper/watches',
        description:
          'Currently active ZooKeeper/Keeper watches registered by this server',
        icon: EyeIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/zookeeper_watches',
        tableCheck: 'system.zookeeper_watches',
      },
      {
        title: 'Keeper Deep-dive',
        href: '/keeper/deep-dive',
        description:
          'Keeper internals (CH 26.6+): Raft cluster membership, snapshot files, and changelog (WAL) disk footprint',
        icon: LayersIcon,
        isNew: true,
      },
    ],
  },
  {
    title: 'PeerDB',
    href: '',
    icon: PeerDBLogo,
    section: 'main',
    isNew: true,
    permission: { feature: 'peerdb' },
    items: [
      {
        title: 'Mirrors',
        href: '/peerdb',
        description:
          'PeerDB replication mirrors with status, throughput, and per-table sync',
        icon: GitCompareArrowsIcon,
        permission: { feature: 'peerdb' },
        docs: 'https://docs.peerdb.io/mirror/overview',
      },
      {
        title: 'Peers',
        href: '/peerdb/peers',
        description:
          'Source and destination peers, replication slot lag, and the mirror graph',
        icon: UnplugIcon,
        permission: { feature: 'peerdb' },
        docs: 'https://docs.peerdb.io/connect/overview',
      },
    ],
  },
  {
    title: 'Security',
    href: '',
    icon: ShieldIcon,
    section: 'others',
    isNew: true,
    permission: { feature: 'security' },
    items: [
      {
        title: 'Sessions',
        href: '/security/sessions',
        description: 'User session history with authentication details',
        icon: UsersIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/session_log',
        tableCheck: 'system.session_log',
      },
      {
        title: 'Login Attempts',
        href: '/security/login-attempts',
        description: 'Authentication events with failure reasons',
        icon: KeyIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/session_log',
        tableCheck: 'system.session_log',
      },
      {
        title: 'Audit Log',
        href: '/security/audit-log',
        description: 'Security-related events and access control',
        icon: ShieldIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/opentelemetry_event_log',
        tableCheck: 'system.session_log',
      },
      {
        title: 'Users',
        href: '/users',
        description:
          'ClickHouse user accounts, authentication types, hosts, and default roles',
        icon: UsersIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/users',
        tableCheck: 'system.users',
      },
      {
        title: 'Roles',
        href: '/roles',
        description: 'Defined roles for role-based access control',
        icon: KeyIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/roles',
        tableCheck: 'system.roles',
      },
    ],
  },
  {
    title: 'Logs',
    href: '',
    icon: ScrollTextIcon,
    section: 'others',
    isNew: true,
    permission: { feature: 'logs' },
    items: [
      {
        title: 'Text Log',
        href: '/logs/text-log',
        description: 'Server logs with query context and stack traces',
        icon: ScrollTextIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/text_log',
        tableCheck: 'system.text_log',
      },
      {
        title: 'Stack Traces',
        href: '/logs/stack-traces',
        description: 'Live thread stack traces for debugging',
        icon: ScrollTextIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/stack_trace',
        tableCheck: 'system.stack_trace',
      },
      {
        title: 'Crashes',
        href: '/logs/crashes',
        description: 'Historical crash reports with diagnostics',
        icon: ShieldAlertIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/crash_log',
        tableCheck: 'system.crash_log',
      },
    ],
  },
  {
    title: 'System',
    href: '',
    icon: GearIcon,
    section: 'others',
    items: [
      {
        title: 'Settings',
        href: '/settings',
        description: 'Server configuration settings and current values',
        countKey: 'settings',
        countLabel: 'settings',
        icon: GearIcon,
        permission: { feature: 'settings' },
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/settings',
        tableCheck: 'system.settings',
      },
      {
        title: 'MergeTree Settings',
        href: '/mergetree-settings',
        description: 'MergeTree engine-specific settings',
        countKey: 'mergetree-settings',
        countLabel: 'settings',
        icon: TableIcon,
        permission: { feature: 'settings' },
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/merge_tree_settings',
        tableCheck: 'system.merge_tree_settings',
      },
      {
        title: 'Replicated MergeTree Settings',
        href: '/replicated-merge-tree-settings',
        description:
          'Replicated MergeTree engine settings and whether each was changed from default',
        icon: SlidersHorizontalIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/replicated_merge_tree_settings',
        tableCheck: 'system.replicated_merge_tree_settings',
      },
      {
        title: 'Disks',
        href: '/disks',
        description: 'Storage disk configuration and usage',
        countKey: 'disks',
        countLabel: 'disks',
        icon: HardDriveIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/disks',
        tableCheck: 'system.disks',
      },
      {
        title: 'Storage Economics',
        href: '/storage-economics',
        description:
          'Per-table compression ratios, storage cost, storage policies, and TTL move activity',
        icon: CircleDollarSignIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/parts',
        tableCheck: 'system.parts',
      },
      {
        title: 'Warnings',
        href: '/warnings',
        description:
          'Server-side warnings about potential configuration or operational issues',
        icon: AlertTriangleIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/warnings',
        tableCheck: 'system.warnings',
      },
    ],
  },
  {
    title: 'Cluster',
    href: '',
    icon: UngroupIcon,
    section: 'others',
    permission: { feature: 'cluster' },
    items: [
      {
        title: 'Clusters',
        href: '/clusters',
        description: 'Interactive topology map and cluster member information',
        countKey: 'clusters',
        countLabel: 'clusters',
        icon: UngroupIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/clusters',
        tableCheck: 'system.clusters',
      },
      {
        title: 'Connections',
        href: '/charts?name=connections-http,connections-interserver',
        description: 'Client and inter-server connection metrics',
        icon: UnplugIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/metrics',
        tableCheck: 'system.metrics',
      },
    ],
  },
  {
    title: 'Operations',
    href: '',
    icon: ArchiveIcon,
    section: 'others',
    permission: { feature: 'operations' },
    items: [
      {
        title: 'Chart Builder',
        href: '/dashboard',
        description: 'Build custom monitoring dashboards with charts',
        icon: DashboardIcon,
        permission: { feature: 'dashboard' },
      },
      {
        title: 'Backups',
        href: '/backups',
        description: 'Backup operation history with status and sizes',
        countKey: 'backups',
        countLabel: 'backups',
        icon: ArchiveIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/backup_log',
        tableCheck: 'system.backup_log',
      },
      {
        title: 'Blob Storage Log',
        href: '/blob-storage-log',
        description:
          'Object storage I/O operations (reads, writes, deletes) on S3/blob disks',
        icon: CloudIcon,
        isNew: true,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/blob_storage_log',
        tableCheck: 'system.blob_storage_log',
      },
      {
        title: 'Errors',
        href: '/errors',
        description: 'Detailed error events with stack traces',
        icon: ShieldAlertIcon,
        docs: 'https://clickhouse.com/docs/en/operations/system-tables/error_log',
        tableCheck: 'system.error_log',
      },
      {
        title: 'Page Views',
        href: '/page-views',
        description: 'Dashboard usage analytics',
        countKey: 'page-views',
        countLabel: 'views',
        icon: BarChartIcon,
        tableCheck: EVENTS_TABLE,
      },
      {
        title: 'MCP Server',
        href: '/mcp',
        description: 'Connect AI assistants via Model Context Protocol',
        icon: UnplugIcon,
        isNew: true,
        permission: { feature: 'mcp' },
      },
      {
        title: 'Docs',
        href: DOCS_SITE_URL,
        description: 'Documentation and usage guides',
        icon: BookOpenIcon,
        permission: { feature: 'docs' },
      },
      {
        title: 'About',
        href: '/about',
        description: 'Dashboard and server version information',
        icon: InfoCircledIcon,
        permission: { feature: 'about' },
      },
    ],
  },
]
