{{- if not .Values.clickhouse.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chmonitor.fullname" . }}
  labels:
    {{- include "chmonitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.password | quote }}
{{- end }}
