import type { QueryConfig } from '@/types/query-config'

import { QUERY_COMMENT } from '@/lib/clickhouse/constants'
import { ColumnFormat } from '@/types/column-format'

export const keeperLogConfig: QueryConfig = {
  name: 'keeper-log',
  description:
    'Per-request log of parameters sent to ZooKeeper/Keeper and the responses received. Requires <zookeeper_log> in server config (often absent in default installs). https://clickhouse.com/docs/en/operations/system-tables/zookeeper_log',
  optional: true,
  tableCheck: 'system.zookeeper_log',
  docs: 'https://clickhouse.com/docs/en/operations/system-tables/zookeeper_log',
  sql: `
      ${QUERY_COMMENT}
      SELECT
        hostname,
        event_time,
        thread_id,
        query_id,
        toString(address) AS address,
        port,
        session_id,
        xid,
        type,
        op_num,
        path,
        data,
        is_ephemeral,
        is_sequential,
        has_watch,
        version,
        requests_size,
        request_idx,
        zxid,
        error,
        watch_type,
        watch_state,
        path_created,
        stat_czxid,
        stat_mzxid,
        stat_pzxid,
        stat_version,
        stat_cversion,
        stat_aversion,
        stat_dataLength,
        stat_numChildren,
        children
      FROM system.zookeeper_log
      WHERE event_time >= now() - INTERVAL 7 DAY
      ORDER BY event_time DESC
      LIMIT 1000
  `,
  columns: [
    'hostname',
    'event_time',
    'thread_id',
    'query_id',
    'address',
    'port',
    'session_id',
    'xid',
    'type',
    'op_num',
    'path',
    'data',
    'is_ephemeral',
    'is_sequential',
    'has_watch',
    'version',
    'requests_size',
    'request_idx',
    'zxid',
    'error',
    'watch_type',
    'watch_state',
    'path_created',
    'stat_czxid',
    'stat_mzxid',
    'stat_pzxid',
    'stat_version',
    'stat_cversion',
    'stat_aversion',
    'stat_dataLength',
    'stat_numChildren',
    'children',
  ],
  columnFormats: {
    hostname: ColumnFormat.Text,
    event_time: ColumnFormat.RelatedTime,
    thread_id: ColumnFormat.Number,
    query_id: ColumnFormat.Text,
    address: ColumnFormat.Text,
    port: ColumnFormat.Number,
    session_id: ColumnFormat.Number,
    xid: ColumnFormat.Number,
    type: ColumnFormat.ColoredBadge,
    op_num: ColumnFormat.ColoredBadge,
    path: ColumnFormat.Code,
    data: ColumnFormat.Text,
    is_ephemeral: ColumnFormat.Boolean,
    is_sequential: ColumnFormat.Boolean,
    has_watch: ColumnFormat.Boolean,
    version: ColumnFormat.Number,
    requests_size: ColumnFormat.Number,
    request_idx: ColumnFormat.Number,
    zxid: ColumnFormat.Number,
    error: ColumnFormat.ColoredBadge,
    watch_type: ColumnFormat.ColoredBadge,
    watch_state: ColumnFormat.ColoredBadge,
    path_created: ColumnFormat.Code,
    stat_czxid: ColumnFormat.Number,
    stat_mzxid: ColumnFormat.Number,
    stat_pzxid: ColumnFormat.Number,
    stat_version: ColumnFormat.Number,
    stat_cversion: ColumnFormat.Number,
    stat_aversion: ColumnFormat.Number,
    stat_dataLength: ColumnFormat.Number,
    stat_numChildren: ColumnFormat.Number,
    children: ColumnFormat.Text,
  },
}
