#!/usr/bin/env bun

import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const ROOT = path.join(process.cwd(), 'docs/content')
const OUT = path.join(
  process.cwd(),
  'app/(docs)/docs/_lib/content.generated.ts'
)

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true })
  const files = await Promise.all(
    entries.map(async (entry) => {
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) return walk(full)
      return entry.isFile() &&
        (entry.name.endsWith('.mdx') || entry.name.endsWith('.md'))
        ? [full]
        : []
    })
  )
  return files.flat()
}

function toSlug(file: string) {
  const rel = path.relative(ROOT, file).replace(/\\/g, '/')
  const noExt = rel.replace(/\.(mdx|md)$/, '')
  return noExt === 'index' ? '' : noExt.replace(/\/index$/, '')
}

const files = (await walk(ROOT)).sort()
const entries = await Promise.all(
  files.map(async (f) => [toSlug(f), await readFile(f, 'utf8')] as const)
)

const body = entries
  .map(
    ([slug, content]) =>
      `  ${JSON.stringify(slug)}: ${JSON.stringify(content)},`
  )
  .join('\n')

const out = `// Generated by scripts/build-docs-content.ts. Do not edit by hand.
export const docsContent: Record<string, string> = {
${body}
}

export type DocsContentSlug = keyof typeof docsContent
`

await writeFile(OUT, out, 'utf8')
console.log(
  `Wrote ${entries.length} docs entries to ${path.relative(process.cwd(), OUT)}`
)
