#!/usr/bin/env bun

/**
 * Generator for the ClickHouse platform support matrix
 *
 * Usage:
 *   bun run scripts/build-support-matrix.ts
 *
 * Writes to:
 *   docs/content/reference/support-matrix.mdx
 *   docs/versions/v0.3/reference/support-matrix.mdx
 */

import { LTS_VERSIONS, SUPPORTED_MAJOR_VERSIONS } from './ch-schema/constants'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

// ---------------------------------------------------------------------------
// Support model
// ---------------------------------------------------------------------------

type SupportLevel = 'supported' | 'best-effort' | 'untested'

type Flavor = {
  name: string
  level: SupportLevel
  notes: string
}

/**
 * What each level means:
 *   supported   — tested in CI or known to work; issues are treated as bugs
 *   best-effort — expected to work but not systematically tested; best-effort fixes
 *   untested    — architecture is compatible but no coverage exists
 */
const FLAVORS: Flavor[] = [
  {
    name: 'ClickHouse OSS',
    level: 'supported',
    notes: 'Primary target. Tested in CI against LTS releases.',
  },
  {
    name: 'Altinity Stable',
    level: 'best-effort',
    notes: 'API-compatible with OSS; community-reported issues only.',
  },
  {
    name: 'ClickHouse Cloud',
    level: 'best-effort',
    notes:
      'Compatible via HTTPS connector; some system tables may be restricted by service tier.',
  },
  {
    name: 'chDB',
    level: 'untested',
    notes: 'Embeds ClickHouse but exposes a different interface. Not tested.',
  },
  {
    name: 'CHProxy',
    level: 'untested',
    notes:
      'Protocol-level proxy; dashboard connects to the upstream cluster directly, not through CHProxy.',
  },
]

// ---------------------------------------------------------------------------
// Version list derived from constants (single source of truth)
// ---------------------------------------------------------------------------

// Expand major versions into representative minor version strings.
// We list LTS versions first (they are the recommended deployment targets),
// then append the current major heads for non-LTS majors.
function buildVersionList(): string[] {
  const ltsSet = new Set<string>(LTS_VERSIONS)

  const result: string[] = [...LTS_VERSIONS]

  for (const major of SUPPORTED_MAJOR_VERSIONS) {
    // If no LTS entry for this major exists yet, represent it as `<major>.x`
    const hasLts = [...ltsSet].some((v) => v.startsWith(`${major}.`))
    if (!hasLts) {
      result.push(`${major}.x`)
    }
  }

  return result
}

// ---------------------------------------------------------------------------
// Level helpers
// ---------------------------------------------------------------------------

const LEVEL_SYMBOL: Record<SupportLevel, string> = {
  supported: '✓',
  'best-effort': '◐',
  untested: '—',
}

const LEVEL_LABEL: Record<SupportLevel, string> = {
  supported: 'Supported',
  'best-effort': 'Best-effort',
  untested: 'Untested',
}

function isLts(version: string): boolean {
  return (LTS_VERSIONS as readonly string[]).includes(version)
}

// ---------------------------------------------------------------------------
// Document renderer
// ---------------------------------------------------------------------------

function render(versions: string[]): string {
  const now = new Date().toISOString().split('T')[0]

  const flavorHeader = FLAVORS.map((f) => f.name).join(' | ')
  const flavorSeparator = FLAVORS.map(() => ':---:').join(' | ')

  const rows = versions.map((ver) => {
    const tag = isLts(ver) ? ' (LTS)' : ''
    const cells = FLAVORS.map((f) => LEVEL_SYMBOL[f.level]).join(' | ')
    return `| ${ver}${tag} | ${cells} |`
  })

  const legendRows = FLAVORS.map(
    (f) =>
      `| ${LEVEL_SYMBOL[f.level]} ${LEVEL_LABEL[f.level]} | **${f.name}** | ${f.notes} |`
  )

  return `# ClickHouse Platform Support Matrix

> **AUTO-GENERATED — do not edit this file directly.**
> Edit \`scripts/build-support-matrix.ts\` and re-run:
> \`\`\`
> bun run scripts/build-support-matrix.ts
> \`\`\`
> Last generated: ${now}

---

chmonitor connects to ClickHouse over the HTTP interface and reads system tables.
This page documents which ClickHouse distributions and versions are tested or expected to work.

## Support levels

| Symbol | Level | Meaning |
|:---:|:---|:---|
| ${LEVEL_SYMBOL.supported} | **Supported** | Tested in CI or known to work end-to-end. Regressions are treated as bugs and fixed promptly. |
| ${LEVEL_SYMBOL['best-effort']} | **Best-effort** | Expected to work based on API compatibility. Not systematically tested. Issues are investigated but fixes are not guaranteed. |
| ${LEVEL_SYMBOL.untested} | **Untested** | Architecture may be compatible but no test coverage exists. Use at your own risk. |

---

## Versions × distributions

| Version | ${flavorHeader} |
|:---|${flavorSeparator}|
${rows.join('\n')}

---

## Distribution notes

| Symbol | Distribution | Notes |
|:---:|:---|:---|
${legendRows.join('\n')}

---

## LTS versions

Long-term support (LTS) releases — currently ${LTS_VERSIONS.join(', ')} — are the recommended deployment targets.
They receive patches for a longer period from the ClickHouse team and are the versions exercised in CI.

Supported major version series: ${[...SUPPORTED_MAJOR_VERSIONS].join(', ')}.
`
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function writeFile(path: string, content: string) {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content, 'utf8')
  console.log(`  wrote ${path}`)
}

function main() {
  console.log('ClickHouse Platform Support Matrix Generator\n')

  const versions = buildVersionList()
  console.log(`  versions: ${versions.join(', ')}`)
  console.log(`  flavors:  ${FLAVORS.map((f) => f.name).join(', ')}\n`)

  const content = render(versions)

  const outputs = [
    'docs/content/reference/support-matrix.mdx',
    'docs/versions/v0.3/reference/support-matrix.mdx',
  ]

  for (const output of outputs) {
    writeFile(output, content)
  }

  console.log('\n✓ Support matrix generated successfully!')
}

main()
