import { execFileSync } from 'node:child_process'

const repo = process.env.GITHUB_REPOSITORY ?? 'duyet/clickhouse-monitoring'
const tag = process.env.RELEASE_TAG ?? process.env.GITHUB_REF_NAME ?? 'v0.0.0'
const version = tag.replace(/^v/, '')
const sha = process.env.GITHUB_SHA ?? ''
const shortSha = sha.slice(0, 7) || 'unknown'
const image = `ghcr.io/${repo}`
const date = new Date().toISOString()
const isPrerelease = version.includes('-')
const major = version.split('.')[0]
const minor = version.split('.').slice(0, 2).join('.')
const stableTagNotes = isPrerelease
  ? '- Prerelease tags do not update the major or major.minor Docker aliases.'
  : `- Stable aliases: \`${image}:${minor}\`, \`${image}:${major}\`, and \`${image}:latest\`.`

function runGit(args: string[]) {
  try {
    return execFileSync('git', args, {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim()
  } catch {
    return ''
  }
}

const previousTag =
  process.env.PREVIOUS_TAG ||
  runGit(['describe', '--tags', '--abbrev=0', `${tag}^`]) ||
  runGit(['describe', '--tags', '--abbrev=0', 'HEAD^'])
const changeRange = previousTag ? `${previousTag}..HEAD` : 'HEAD'
const gitChanges =
  runGit(['log', '--pretty=format:- %s (%h)', changeRange]) ||
  '- No git changes were detected by the release note generator.'
const compareUrl = previousTag
  ? `https://github.com/${repo}/compare/${previousTag}...${tag}`
  : `https://github.com/${repo}/commits/${tag}`

const notes = `# ClickHouse Monitor ${tag}

Built from commit \`${shortSha}\` on ${date}.

## What is included

- Next.js standalone server archive for self-hosted Node.js deployments.
- Cloudflare Workers/OpenNext archive for inspection or manual Workers deployment.
- Multi-architecture Docker images for linux/amd64 and linux/arm64.
- SHA256 checksums for release archives.

## Install the app CLI commands

This repository does not publish a separate global npm CLI. Use the checked-out release with Bun and the bundled package scripts:

\`\`\`bash
git clone https://github.com/${repo}.git
cd clickhouse-monitoring
git checkout ${tag}
bun install --frozen-lockfile
\`\`\`

Common commands:

\`\`\`bash
bun run dev          # local development server
bun run build        # Next.js standalone build
bun run cf:build     # Cloudflare Workers/OpenNext build
bun run cf:deploy    # set Workers secrets, build, and deploy
bun run cf:preview   # local Cloudflare Workers preview
\`\`\`

For Cloudflare, install Wrangler if it is not already available:

\`\`\`bash
bunx wrangler login
\`\`\`

## Required configuration

Set these values before running or deploying:

| Variable | Required | Description |
| --- | --- | --- |
| \`CLICKHOUSE_HOST\` | Yes | ClickHouse HTTP endpoint. Use comma-separated values for multiple hosts. |
| \`CLICKHOUSE_USER\` | Yes | ClickHouse user. Use comma-separated values to match multiple hosts. |
| \`CLICKHOUSE_PASSWORD\` | Yes | ClickHouse password. Use comma-separated values to match multiple hosts. |
| \`CLICKHOUSE_NAME\` | No | Display names for hosts. |
| \`CLICKHOUSE_TZ\` | No | ClickHouse timezone. |
| \`CLICKHOUSE_MAX_EXECUTION_TIME\` | No | Query timeout in seconds. |
| \`NEXT_QUERY_CACHE_TTL\` | No | Query cache TTL in seconds. |

## Docker

Use the release tag for repeatable deployments:

\`\`\`bash
docker run -d \\
  --name clickhouse-monitor \\
  -p 3000:3000 \\
  -e CLICKHOUSE_HOST=https://your-clickhouse-host.com \\
  -e CLICKHOUSE_USER=default \\
  -e CLICKHOUSE_PASSWORD=yourpassword \\
  ${image}:${version}
\`\`\`

Published Docker tags:

- \`${image}:${version}\`
${stableTagNotes}
- Commit tag: \`${image}:sha-${shortSha}\`

## Cloudflare Workers deploy

Create a local \`.env.local\` with the required ClickHouse values, then run:

\`\`\`bash
bunx wrangler login
bun run cf:config
bun run cf:build
bunx wrangler deploy
\`\`\`

The shorthand command does the same secret sync, build, and deploy sequence:

\`\`\`bash
bun run cf:deploy
\`\`\`

## Release archives

- \`clickhouse-monitor-${tag}-standalone.tar.gz\`: Next.js standalone output for Node.js runtime.
- \`clickhouse-monitor-${tag}-cloudflare.tar.gz\`: OpenNext Cloudflare output and Workers config.
- \`SHA256SUMS\`: checksum file for both archives.
- \`release-notes.md\`: this release note as generated by CI.

## Verify deployment

After deployment, check:

\`\`\`bash
curl -sSf https://your-domain.example/api/healthz
curl -sSf https://your-domain.example/api/version
\`\`\`

## Git changes

${gitChanges}

Complete diff: ${compareUrl}
`

process.stdout.write(notes)
