#!/usr/bin/env bun

/**
 * Generate skill documentation from codebase
 *
 * This script dynamically scans the codebase to generate comprehensive
 * API documentation for the Agent Skill.
 *
 * Usage: bun run scripts/generate-skill-docs.ts
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'fs'
import { join } from 'path'

const ROOT = process.cwd()
const SKILL_DIR = join(ROOT, 'skills')

// Types extracted from the codebase
interface ChartModule {
  charts: Record<string, { description?: string }>
}

interface QueryConfig {
  name: string
  description?: string
}

/**
 * Recursively find all files matching a pattern
 */
function findFiles(dir: string, pattern: RegExp): string[] {
  const files: string[] = []

  function traverse(currentPath: string) {
    const entries = readdirSync(currentPath)

    for (const entry of entries) {
      const fullPath = join(currentPath, entry)
      const stat = statSync(fullPath)

      if (stat.isDirectory()) {
        // Skip node_modules and hidden directories
        if (!entry.startsWith('.') && entry !== 'node_modules') {
          traverse(fullPath)
        }
      } else if (stat.isFile() && pattern.test(entry)) {
        files.push(fullPath)
      }
    }
  }

  traverse(dir)
  return files
}

/**
 * Extract chart names from domain chart modules
 */
function extractChartNames(): string[] {
  const chartFiles = findFiles(join(ROOT, 'lib/api/charts'), /-charts\.ts$/)

  const allCharts: Set<string> = new Set()

  for (const filePath of chartFiles) {
    try {
      const content = readFileSync(filePath, 'utf-8')

      // Extract chart names from export const xxxCharts = { ... }
      // Pattern: 'chart-name': ({ ... }) => ({
      const chartRegex = /'([^']+)':\s*\(/g
      let match
      while ((match = chartRegex.exec(content)) !== null) {
        allCharts.add(match[1])
      }
    } catch (e) {
      console.warn(`Could not read ${filePath}:`, e.message)
    }
  }

  return Array.from(allCharts).sort()
}

/**
 * Extract query config names from query-config files
 */
function extractQueryConfigNames(): string[] {
  const queryFiles = findFiles(join(ROOT, 'lib/query-config'), /\.ts$/)

  const configs: Set<string> = new Set()

  for (const filePath of queryFiles) {
    try {
      const content = readFileSync(filePath, 'utf-8')

      // Extract config name: export const xxxConfig: QueryConfig = {
      const configRegex = /export\s+const\s+(\w+)Config:\s*QueryConfig/g
      let match
      while ((match = configRegex.exec(content)) !== null) {
        const name = match[1]
          .replace(/([A-Z])/g, '-$1')
          .toLowerCase()
          .replace(/^-/, '')
        configs.add(name)
      }
    } catch (e) {
      console.warn(`Could not read ${filePath}:`, e.message)
    }
  }

  return Array.from(configs).sort()
}

/**
 * Generate API reference section
 */
function generateAPIReference(
  chartNames: string[],
  queryNames: string[]
): string {
  return `# API Reference

This section lists all available API endpoints. Auto-generated from codebase.

## Chart Data Endpoints

All chart endpoints follow this pattern:

\`\`\`http
GET /api/v1/charts/{chartName}?hostId={hostId}&interval={interval}&lastHours={hours}
\`\`\`

### Available Charts (${chartNames.length} total)

${chartNames.map((name) => `- \`${name}\``).join('\n')}

## Table Data Endpoints

All table endpoints follow this pattern:

\`\`\`http
GET /api/v1/tables/{queryConfigName}?hostId={hostId}&pageSize={n}&page={p}
\`\`\`

### Available Table Queries (${queryNames.length} total)

${queryNames.map((name) => `- \`${name}\``).join('\n')}

## Explorer Endpoints

\`\`\`http
GET /api/v1/explorer/databases?hostId={hostId}
GET /api/v1/explorer/tables?hostId={hostId}&database={db}
GET /api/v1/explorer/columns?hostId={hostId}&database={db}&table={t}
GET /api/v1/explorer/dependencies?hostId={hostId}&database={db}&table={t}
GET /api/v1/explorer/ddl?hostId={hostId}&database={db}&table={t}
GET /api/v1/explorer/projections?hostId={hostId}&database={db}&table={t}
GET /api/v1/explorer/indexes?hostId={hostId}&database={db}&table={t}
GET /api/v1/explorer/dictionary-source?hostId={hostId}
\`\`\`

## System Endpoints

\`\`\`http
GET /api/v1/hosts  # List configured ClickHouse hosts
\`\`\`

---
*Generated by \`scripts/generate-skill-docs.ts\` from ${new Date().toISOString()}*
`
}

/**
 * Generate dashboard pages reference
 */
function generateDashboardPages(): string {
  // Read menu.ts to extract page structure
  const menuPath = join(ROOT, 'menu.ts')
  const menuContent = readFileSync(menuPath, 'utf-8')

  // Parse menu items using a more robust approach
  // Look for objects with title, href, description properties
  const itemRegex =
    /{\s*title:\s*['"]([^'"]+)['"][\s\S]*?href:\s*['"]([^'"]+)['"][\s\S]*?description:\s*['"]([^'"]+)['"]/g

  const pages: Array<{ title: string; href: string; description: string }> = []

  let match
  while ((match = itemRegex.exec(menuContent)) !== null) {
    pages.push({
      title: match[1],
      href: match[2],
      description: match[3],
    })
  }

  // Also look for simpler items without description
  const simpleRegex =
    /{\s*title:\s*['"]([^'"]+)['"][\s\S]*?href:\s*['"]([^'"]+)['"]/g
  while ((match = simpleRegex.exec(menuContent)) !== null) {
    // Skip if already added
    if (!pages.some((p) => p.title === match[1] && p.href === match[2])) {
      pages.push({
        title: match[1],
        href: match[2],
        description: '',
      })
    }
  }

  // Filter out parent items (empty href or query-only href)
  const leafPages = pages.filter(
    (p) => p.href && p.href !== '' && !p.href.includes('?name=')
  )

  return `# Dashboard Pages

Complete list of all dashboard pages (${leafPages.length} total).

| Page | Path | Description |
|------|------|-------------|
${leafPages
  .map(
    (page) =>
      `| **${page.title}** | \`${page.href || '/'}\` | ${page.description} |`
  )
  .join('\n')}

---
*Generated by \`scripts/generate-skill-docs.ts\` from ${new Date().toISOString()}*
`
}

/**
 * Main execution
 */
function main() {
  console.log('🔍 Scanning codebase for API endpoints...')

  const chartNames = extractChartNames()
  console.log(`   Found ${chartNames.length} chart endpoints`)

  const queryNames = extractQueryConfigNames()
  console.log(`   Found ${queryNames.length} table query endpoints`)

  // Generate API reference
  const apiReference = generateAPIReference(chartNames, queryNames)
  writeFileSync(join(SKILL_DIR, 'references/api-list.md'), apiReference)
  console.log('✅ Generated references/api-list.md')

  // Generate dashboard pages reference
  const dashboardPages = generateDashboardPages()
  writeFileSync(
    join(SKILL_DIR, 'references/dashboard-pages.md'),
    dashboardPages
  )
  console.log('✅ Generated references/dashboard-pages.md')

  console.log('\n📚 Skill documentation updated successfully!')
  console.log('\nNext steps:')
  console.log('  1. Review the generated files')
  console.log('  2. Update SKILL.md to reference the new sections')
  console.log('  3. Commit the changes')
}

main()
