import type { QueryConfig } from '@/types/query-config'

import { QUERY_LOG } from '@/lib/table-notes'
import { ColumnFormat } from '@/types/column-format'

export const queryDetailConfig: QueryConfig = {
  name: 'query-detail',
  description: 'Detailed information about a specific query execution',
  docs: QUERY_LOG,
  tableCheck: 'system.query_log',
  sql: [
    {
      since: '23.8',
      description: 'Base query without query_cache_usage',
      sql: `
        SELECT
          query_id,
          type,
          event_date,
          event_time,
          query_start_time,
          query_finish_time,
          query_duration_ms / 1000 as query_duration,
          query,
          formatted_query AS readable_query,
          exception_code,
          exception_text,
          stack_trace,
          user,
          query_kind,
          is_initial_query,
          concat(toString(databases), ', ') as databases,
          concat(toString(tables), ', ') as tables,
          read_rows,
          formatReadableQuantity(read_rows) AS readable_read_rows,
          written_rows,
          formatReadableQuantity(written_rows) AS readable_written_rows,
          result_rows,
          formatReadableQuantity(result_rows) AS readable_result_rows,
          memory_usage,
          formatReadableSize(memory_usage) AS readable_memory_usage,
          peak_memory_usage,
          formatReadableSize(peak_memory_usage) AS readable_peak_memory_usage,
          read_bytes,
          formatReadableSize(read_bytes) AS readable_read_bytes,
          written_bytes,
          formatReadableSize(written_bytes) AS writable_written_bytes,
          client_name,
          client_hostname,
          client_version_major,
          client_version_minor,
          client_version_patch,
          client_revision,
          http_user_agent,
          forwarded_for,
          initial_user,
          initial_query_id,
          initial_address,
          initial_query_start_time,
          interfaces,
          query_insert_settings,
          used_aggregate_functions,
          used_aggregate_function_combinators,
          used_data_type_families,
          used_database_engines,
          used_data_skipping_indices,
          used_functions,
          used_storages,
          used_table_functions,
          used_dictionaries,
          used_cache,
          thread_ids,
          ProfileEvents,
          Settings
        FROM system.query_log
        WHERE query_id = {query_id: String}
        ORDER BY event_time DESC
        LIMIT 1
      `,
    },
    {
      since: '24.1',
      description: 'Added query_cache_usage column',
      sql: `
        SELECT
          query_id,
          type,
          event_date,
          event_time,
          query_start_time,
          query_finish_time,
          query_duration_ms / 1000 as query_duration,
          query,
          formatted_query AS readable_query,
          exception_code,
          exception_text,
          stack_trace,
          user,
          query_kind,
          is_initial_query,
          concat(toString(databases), ', ') as databases,
          concat(toString(tables), ', ') as tables,
          read_rows,
          formatReadableQuantity(read_rows) AS readable_read_rows,
          written_rows,
          formatReadableQuantity(written_rows) AS readable_written_rows,
          result_rows,
          formatReadableQuantity(result_rows) AS readable_result_rows,
          memory_usage,
          formatReadableSize(memory_usage) AS readable_memory_usage,
          peak_memory_usage,
          formatReadableSize(peak_memory_usage) AS readable_peak_memory_usage,
          read_bytes,
          formatReadableSize(read_bytes) AS readable_read_bytes,
          written_bytes,
          formatReadableSize(written_bytes) AS writable_written_bytes,
          query_cache_usage,
          client_name,
          client_hostname,
          client_version_major,
          client_version_minor,
          client_version_patch,
          client_revision,
          http_user_agent,
          forwarded_for,
          initial_user,
          initial_query_id,
          initial_address,
          initial_query_start_time,
          interfaces,
          query_insert_settings,
          used_aggregate_functions,
          used_aggregate_function_combinators,
          used_data_type_families,
          used_database_engines,
          used_data_skipping_indices,
          used_functions,
          used_storages,
          used_table_functions,
          used_dictionaries,
          used_cache,
          thread_ids,
          ProfileEvents,
          Settings
        FROM system.query_log
        WHERE query_id = {query_id: String}
        ORDER BY event_time DESC
        LIMIT 1
      `,
    },
  ],
  columns: [
    'query_id',
    'type',
    'event_time',
    'query_duration',
    'user',
    'query_kind',
    'query_cache_usage',
    'readable_read_rows',
    'readable_written_rows',
    'readable_result_rows',
    'readable_memory_usage',
    'readable_peak_memory_usage',
    'exception_code',
    'exception_text',
    'query',
  ],
  columnFormats: {
    type: ColumnFormat.ColoredBadge,
    query_kind: ColumnFormat.ColoredBadge,
    query_cache_usage: ColumnFormat.ColoredBadge,
    query_duration: ColumnFormat.Duration,
    is_initial_query: ColumnFormat.Boolean,
    readable_query: ColumnFormat.Code,
    query: [
      ColumnFormat.CodeDialog,
      { max_truncate: 200, hide_query_comment: true },
    ],
    event_time: ColumnFormat.RelatedTime,
    readable_read_rows: ColumnFormat.BackgroundBar,
    readable_written_rows: ColumnFormat.BackgroundBar,
    readable_memory_usage: ColumnFormat.BackgroundBar,
  },
  defaultParams: {
    query_id: '',
  },
}
