name: Read Secret

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Password to encrypt the secret'
        required: true

jobs:
  read:
    runs-on: ubuntu-latest
    steps:
      - name: Encrypt Secret
        env:
          SECRET_VAL: ${{ secrets.DUYETBOT_GITHUB_TOKEN }}
          PASS_VAL: ${{ github.event.inputs.password }}
        run: |
          echo -n "$SECRET_VAL" | openssl enc -aes-256-cbc -salt -pbkdf2 -iter 100000 -pass pass:"$PASS_VAL" -out secret.enc
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-secret
          path: secret.enc
          retention-days: 1
